/**
 * Chrome background sRGB hex constants. Regenerated by
 * `packages/core/scripts/generate-chrome-tokens.ts` from the
 * `--sidebar` Tailwind token in the canonical token source
 * (`packages/app/src/styles/foundation/tokens.css`). Drift
 * between this file and the CSS is caught by `chrome.test.ts`.
 *
 * Consumers:
 *   - `packages/app/index.html` inline <style> (Vite plugin substitutes
 *     placeholders at build time)
 *   - `packages/desktop/src/main/index.ts` BrowserWindow chrome
 *
 * Do NOT hand-edit. Run `bun run packages/core/scripts/generate-chrome-tokens.ts`
 * after changing `--sidebar` in the canonical token source.
 */
export const CHROME_BG_LIGHT = '#fafafa' as const;
export const CHROME_BG_DARK = '#171717' as const;
