import { previewDatabaseSelectOptionChange } from '@nedian0brien/synapsenote-core';
import {
  createDatabaseBulkCellMutationDesiredState,
  createDatabaseBulkCheckboxToggleDesiredState,
  createDatabasePageAppearanceDesiredState,
  createDatabasePageTitleDesiredState,
  createDatabaseSelectOptionChangeDesiredState,
  createDatabaseTablePasteDesiredState,
} from '@/lib/database-cell-mutation';
import {
  databaseDelimitedRecordIds,
  inspectDatabaseImport,
  planDatabaseDelimitedImport,
} from '@/lib/database-csv';
import { databaseSnapshotToJson } from '@/lib/database-json';
import {
  applyDatabaseUiRedo,
  applyDatabaseUiUndo,
  executeDatabaseUiMutation,
  previewDatabaseUiRedo,
  previewDatabaseUiUndo,
} from '@/lib/database-mutation-client';
import { appendDatabaseQueryPage } from '@/lib/database-query-client';
import { databaseRecordsToTsv } from '@/lib/database-tsv';
import { classifyDatabaseUiProblem, databaseConflictProblem } from '@/lib/database-ui-problem';
import {
  databaseBrowserLoadedRecordLimit,
  databaseBrowserNextPageLimit,
} from '@/lib/database-view-bounds';
import { saveDatabaseLastOpenedView } from '@/lib/database-view-state';
import {
  type DatabaseSelectProperty,
  downloadTextFile,
  isDatabaseSelectProperty,
} from './DatabaseTableGrid';
import type { DatabaseTableDialogProps } from './database-workspace-types';
import type { useDatabaseWorkspaceControllerState } from './use-database-workspace-controller-state';
import type { useDatabaseWorkspaceMutationRecordCommands } from './use-database-workspace-mutation-record-commands';
import { useDatabaseWorkspaceBulkCommands } from './useDatabaseWorkspaceBulkCommands';
import { useDatabaseWorkspaceSchemaCommands } from './useDatabaseWorkspaceSchemaCommands';
import { useDatabaseWorkspaceViewCommands } from './useDatabaseWorkspaceViewCommands';

type WorkspaceState = ReturnType<typeof useDatabaseWorkspaceControllerState>;
type BulkInput = Parameters<typeof useDatabaseWorkspaceBulkCommands>[0];
type ViewInput = Parameters<typeof useDatabaseWorkspaceViewCommands>[0];

/** Owns typed bulk, schema, and saved-view command input construction. */
export function useDatabaseWorkspaceStructureCommands({
  props,
  state,
  description,
  result,
  catalogStatus,
  tableStatus,
  databasePageTitle,
  isCanvasPresentation,
  isPagePresentation,
  mutationRecordCommands,
}: {
  props: DatabaseTableDialogProps;
  state: WorkspaceState;
  description: BulkInput['description'];
  result: BulkInput['result'];
  catalogStatus: ViewInput['catalogStatus'];
  tableStatus: ViewInput['tableStatus'];
  databasePageTitle: ViewInput['databasePageTitle'];
  isCanvasPresentation: boolean;
  isPagePresentation: boolean;
  mutationRecordCommands: ReturnType<typeof useDatabaseWorkspaceMutationRecordCommands>;
}) {
  const {
    open,
    initialDatabaseSurface,
    initialViewAction,
    initialPropertyId,
    initialSelectedRecordIds,
    initialTablePaste,
    initialAction,
    initialTarget,
    onOpenChange,
    onOpenContextInspector,
    onOpenAgentRuns,
  } = props;
  const {
    optionPropertyId,
    optionId,
    optionName,
    optionColor,
    optionMergeTargetId,
    setOptionPreview,
    setOptionStatus,
    optionPreview,
    setPropertyDeletionPreview,
    setPropertiesError,
    setPropertiesRemoveStatus,
    propertiesRemoveStatus,
    mutationStatus,
    setMutationStatus,
    csvStatus,
    setCsvStatus,
    importPreview,
    setImportPreview,
    setLastUndoToken,
    setLastRedoToken,
    lastUndoToken,
    lastRedoToken,
    selection,
    optionStatus,
    setPropertiesDialogOpen,
    setPropertiesDialogRenameId,
    undoStatus,
    setUndoStatus,
    setSelectedRecordIds,
    setRefresh,
    setOptimisticViewOrder,
    redoStatus,
    setRedoStatus,
    selectedViewId,
    pageStatus,
    setPageStatus,
    pageCursor,
    setPageCursor,
    locallyHandledRecordIdsRef,
    buttonStatus,
    optimisticViewOrder,
    agentScopeOverride,
    setAgentScopeOverride,
    setFilterDialogOpen,
    setViewSettingsOpen,
    setViewManagerOpen,
    setSelectedViewId,
    setTableCalculations,
    tableViewStatesRef,
    tableCalculations,
    showArchived,
    pageTitleDraft,
    setPageTitleEditing,
    pageFavorite,
    setPageFavorite,
    setViewRenameTarget,
    setPageError,
    reviewResolverRef,
    setGhost,
    setButtonPlan,
    setButtonStatus,
    setDraggedViewId,
    setDragOverViewId,
    setOptionPropertyId,
    setOptionId,
    setOptionName,
    setOptionColor,
    setOptionMergeTargetId,
    setSelectOptionsOpen,
    computedPropertyId,
    uniqueIdPropertyId,
    placePropertyId,
    buttonPropertyId,
    conversionPropertyId,
    selectedRecordIds,
    setPropertyFilterTargetId,
    setPropertySortTargetId,
    viewRenameTarget,
    setAppearanceOpen,
    setMutationError,
    handledInitialDatabaseSurfaceRef,
    handledInitialSelectedRecordIdsRef,
    preserveSelectionOnRefreshRef,
    pageTitleInputRef,
    setMoveRecord,
    moveRecord,
    setMoveTargetSourceId,
    setComputedPropertyId,
    setUniqueIdPropertyId,
    setPlacePropertyId,
    setButtonPropertyId,
    setConversionPropertyId,
    relationCandidates,
    bulkPropertyId,
    bulkDraft,
    setBulkDraft,
    setBulkPropertyId,
  } = state;
  const commandSelectProperties =
    description?.source?.properties.filter(isDatabaseSelectProperty) ?? [];
  const commandSelectedOptionProperty = commandSelectProperties.find(
    (property) => property.id === optionPropertyId,
  );
  const commandSelectedOption = commandSelectedOptionProperty?.options.find(
    (option) => option.id === optionId,
  );
  const commandCanonicalSourceViews =
    description?.database.views.filter((view) => view.sourceId === description.source?.id) ?? [];
  const commandSourceViews = optimisticViewOrder
    ? [
        ...optimisticViewOrder.flatMap((viewId) =>
          commandCanonicalSourceViews.filter((view) => view.id === viewId),
        ),
        ...commandCanonicalSourceViews.filter((view) => !optimisticViewOrder.includes(view.id)),
      ]
    : commandCanonicalSourceViews;
  const commandSelectedView = commandSourceViews.find((view) => view.id === selectedViewId);
  const commandOpenSelectOptions = (property: DatabaseSelectProperty) => {
    const firstOption = property.options[0];
    setOptionPropertyId(property.id);
    setOptionId(firstOption?.id ?? '');
    setOptionName(firstOption?.name ?? '');
    setOptionColor(firstOption?.color ?? '');
    setOptionMergeTargetId(
      property.options.find((option) => option.id !== firstOption?.id && option.archived !== true)
        ?.id ?? '',
    );
    setOptionPreview(null);
    setSelectOptionsOpen(true);
  };
  const bulkCommands = useDatabaseWorkspaceBulkCommands({
    description,
    result,
    selectedRecordIds,
    bulkPropertyId,
    bulkDraft,
    setBulkDraft,
    setBulkPropertyId,
    setMutationError,
    classifyDatabaseUiProblem,
    mutationStatus,
    runMutation: mutationRecordCommands.runMutation,
    createDatabaseBulkCellMutationDesiredState,
    createDatabaseBulkCheckboxToggleDesiredState,
    createDatabaseTablePasteDesiredState,
    relationCandidates,
    searchRelationCandidates: mutationRecordCommands.searchRelationCandidates,
    setSelectedRecordIds,
    setRefresh,
    selectedView: commandSelectedView,
    initialDatabaseSurface,
    initialViewAction,
    initialPropertyId,
    handledInitialDatabaseSurface: handledInitialDatabaseSurfaceRef,
    setPropertiesDialogRenameId,
    setPropertiesDialogOpen,
    openSelectOptions: commandOpenSelectOptions,
    setViewRenameTarget,
    commitDefaultViewChange: mutationRecordCommands.commitDefaultViewChange,
    setViewManagerOpen,
    setFilterDialogOpen,
    setViewSettingsOpen,
    initialSelectedRecordIds,
    handledInitialSelectedRecordIds: handledInitialSelectedRecordIdsRef,
    selection,
    showArchived,
    csvStatus,
    setCsvStatus,
    databaseSnapshotToJson,
    initialTablePaste,
    handledInitialTablePaste: state.handledInitialTablePasteRef,
    open,
    databaseRecordsToTsv,
    downloadTextFile,
  });
  const schemaCommands = useDatabaseWorkspaceSchemaCommands({
    selectedOption: commandSelectedOption,
    selectedOptionProperty: commandSelectedOptionProperty,
    optionName,
    optionColor,
    optionMergeTargetId,
    setOptionPreview,
    setOptionStatus,
    previewDatabaseSelectOptionChange,
    description,
    setMutationError,
    classifyDatabaseUiProblem,
    optionPreview,
    runMutation: mutationRecordCommands.runMutation,
    createDatabaseSelectOptionChangeDesiredState,
    setPropertyDeletionPreview,
    setPropertiesError,
    setPropertiesRemoveStatus,
    propertiesRemoveStatus,
    mutationStatus,
    setMutationStatus,
    result,
    csvStatus,
    setCsvStatus,
    importPreview,
    setImportPreview,
    databaseDelimitedRecordIds,
    inspectDatabaseImport,
    planDatabaseDelimitedImport,
    databaseRecordsToTsv,
    databaseSnapshotToJson,
    downloadTextFile,
    setLastUndoToken,
    setLastRedoToken,
    lastUndoToken,
    lastRedoToken,
    applyDatabaseUiUndo,
    applyDatabaseUiRedo,
    previewDatabaseUiUndo,
    previewDatabaseUiRedo,
    executeDatabaseUiMutation,
    selection,
    runReviewedPlan: mutationRecordCommands.runReviewedPlan,
    optionStatus,
    optionPropertyId,
    collectDatabaseSnapshot: bulkCommands.collectDatabaseSnapshot,
    selectedView: commandSelectedView,
    setPropertiesDialogOpen,
    setPropertiesDialogRenameId,
    undoStatus,
    setUndoStatus,
    setSelectedRecordIds,
    setRefresh,
    setOptimisticViewOrder,
    redoStatus,
    setRedoStatus,
  });
  const viewCommands = useDatabaseWorkspaceViewCommands({
    description,
    selectedViewId,
    databaseBrowserLoadedRecordLimit,
    databaseBrowserNextPageLimit,
    pageStatus,
    setPageStatus,
    pageCursor,
    setPageCursor,
    result,
    appendDatabaseQueryPage,
    setRefresh,
    locallyHandledRecordIdsRef,
    mutationStatus,
    buttonStatus,
    isCanvasPresentation,
    optionId,
    optimisticViewOrder,
    selection,
    agentScopeOverride,
    setAgentScopeOverride,
    setOptionPreview,
    setFilterDialogOpen,
    setViewSettingsOpen,
    setViewManagerOpen,
    setPropertyDeletionPreview,
    setPropertiesDialogOpen,
    setSelectedRecordIds,
    saveDatabaseLastOpenedView,
    commitSavedViewConfiguration: mutationRecordCommands.commitSavedViewConfiguration,
    commitDefaultViewChange: mutationRecordCommands.commitDefaultViewChange,
    setAgentMenuOpen: state.setAgentMenuOpen,
    setSelectedViewId,
    setTableCalculations,
    tableViewStatesRef,
    tableViewStateKey: `${selection?.sourceId ?? ''}:${selectedViewId || '__all__'}`,
    tableCalculations,
    showArchived,
    pageTitleDraft,
    setPageTitleEditing,
    databasePageTitle,
    pageFavorite,
    setPageFavorite,
    setViewRenameTarget,
    setPageError,
    undoStatus,
    redoStatus,
    lastUndoToken,
    lastRedoToken,
    redoLastChange: schemaCommands.redoLastChange,
    undoLastChange: schemaCommands.undoLastChange,
    reviewResolver: reviewResolverRef,
    setGhost,
    setMutationStatus,
    setButtonPlan,
    setButtonStatus,
    setOptimisticViewOrder,
    setDraggedViewId,
    setDragOverViewId,
    catalogStatus,
    tableStatus,
    optionPropertyId,
    setOptionPropertyId,
    setOptionId,
    setOptionName,
    setOptionColor,
    setOptionMergeTargetId,
    setSelectOptionsOpen,
    computedPropertyId,
    uniqueIdPropertyId,
    placePropertyId,
    buttonPropertyId,
    conversionPropertyId,
    selectedRecordIds,
    setPropertyFilterTargetId,
    setPropertySortTargetId,
    viewRenameTarget,
    setAppearanceOpen,
    setMutationError,
    runMutation: mutationRecordCommands.runMutation,
    createDatabasePageTitleDesiredState,
    createDatabasePageAppearanceDesiredState,
    databaseConflictProblem,
    isPagePresentation,
    open,
    initialViewAction,
    initialPropertyId,
    initialDatabaseSurface,
    handledInitialDatabaseSurface: handledInitialDatabaseSurfaceRef,
    handledInitialSelectedRecordIds: handledInitialSelectedRecordIdsRef,
    initialSelectedRecordIds,
    preserveSelectionOnRefreshRef,
    initialAction,
    initialTarget,
    onOpenChange,
    setPageTitleDraft: state.setPageTitleDraft,
    pageTitleInputRef,
    setMoveRecord,
    moveRecord,
    editCell: mutationRecordCommands.editCell,
    createAndAssignSelectOption: mutationRecordCommands.createAndAssignSelectOption,
    reorderSelectOptions: mutationRecordCommands.reorderSelectOptions,
    changeVerification: mutationRecordCommands.changeVerification,
    deleteRecord: mutationRecordCommands.deleteRecord,
    duplicateRecord: mutationRecordCommands.duplicateRecord,
    changeArchiveState: mutationRecordCommands.changeArchiveState,
    planTablePaste: bulkCommands.planTablePaste,
    searchRelationCandidates: mutationRecordCommands.searchRelationCandidates,
    planBoardTransition: bulkCommands.planBoardTransition,
    planTimelineChange: bulkCommands.planTimelineChange,
    planCalendarChange: bulkCommands.planCalendarChange,
    setMoveTargetSourceId,
    createRecord: mutationRecordCommands.createRecord,
    setComputedPropertyId,
    setUniqueIdPropertyId,
    setPlacePropertyId,
    setButtonPropertyId,
    setConversionPropertyId,
    onOpenContextInspector,
    onOpenAgentRuns,
    setPropertiesDialogRenameId,
  });
  return { ...bulkCommands, ...schemaCommands, ...viewCommands };
}
