export {
  createWorkspace as create,
  updateWorkspace as update,
  openWorkspace as open,
  deleteWorkspace as remove,
  leaveWorkspace as leave,
  getWorkspaces as getAll,
  getWorkspaceFolder as getFolder,
  inviteMembers,
  getMembers,
  getMentionableUsers,
  updatePageMention,
  joinWorkspaceByInvitationCode as joinByInvitationCode,
  getWorkspaceInfoByInvitationCode as getInfoByInvitationCode,
  getGuestInvitation,
  acceptGuestInvitation,
  getGuestToMemberConversionInfo,
  approveTurnGuestToMember,
  addRecentPages,
  updatePublishNamespace,
} from '../js-services/http/workspace-api';
