import type {
  AgentDataCatalogNotModifiedResultV1,
  AgentDataCommitInputV1,
  AgentDataContextInspectionSummaryV1,
  AgentDataContextInspectionV1,
  AgentDataContextPackV1,
  AgentDataPlanArtifactV1,
  AgentDataRelationExpansionInputV1,
  AgentDataRelationExpansionV1,
  AgentDataRepairPlanV1,
  AgentDataTaskRequestV1,
  AgentDataTaskResponseV1,
  AgentDataTaskV1,
  AgentDataUndoResultV1,
  DatabaseAgentViewConfigV1,
  DatabaseDateValueV1,
  DatabaseFileValueV1,
  DatabaseManifestV1,
  DatabasePersonV1,
  DatabaseQueryV1,
  DatabaseTransactionReceiptV1,
  ProjectedDatabaseRelationRecordV1,
} from './index.ts';

declare const publicContracts: readonly [
  DatabaseManifestV1,
  DatabasePersonV1,
  DatabaseDateValueV1,
  DatabaseFileValueV1,
  ProjectedDatabaseRelationRecordV1,
  DatabaseAgentViewConfigV1,
  DatabaseQueryV1,
  DatabaseTransactionReceiptV1,
  AgentDataPlanArtifactV1,
  AgentDataCommitInputV1,
  AgentDataUndoResultV1,
  AgentDataContextPackV1,
  AgentDataContextInspectionSummaryV1,
  AgentDataContextInspectionV1,
  AgentDataCatalogNotModifiedResultV1,
  AgentDataRepairPlanV1,
  AgentDataTaskV1,
  AgentDataTaskRequestV1,
  AgentDataTaskResponseV1,
  AgentDataRelationExpansionInputV1,
  AgentDataRelationExpansionV1,
];

void publicContracts;
